### ISSUE TITLE
Add classNames Props

### ISSUE THREAD

**Issue by Demandtech** [EOEboh/react-one-time-password#1]
I'd like to propose adding className props to all child components. This will allow users to pass in utility classes (such as those from Tailwind CSS or other utility-based frameworks) for more granular styling control and flexibility.

Adding className props would provide:

### Greater Customization
Users can apply their own styles directly to each child component, enabling easier and more precise customization.

### Improved Integration: 
It facilitates the use of utility-first CSS frameworks like Tailwind CSS, making the components more adaptable to various design needs.

### Consistent Development Experience
Standardizing the use of className across all components will help developers know exactly how to style them.

If this proposal is approved, I would be happy to work on implementing it.

Thank you for considering this suggestion!

**Comment by EOEboh** [comment]
Hey @Demandtech 
Thank you for opening this issue. This seems like a great idea. 

I’ll write a style guide this morning and get back to you later today, then you will make add the feature and make a PR

**Comment by Demandtech** [comment]
Okay @EOEboh, I will wait for your update.

**Comment by EOEboh** [comment]
Hello @Demandtech, You can go ahead and add what you've talked about. Then open a PR

Just make sure the classNames are in `kebab-case`. I await your PR
