### ISSUE TITLE
Interactive Demo Proposal

### ISSUE THREAD

**Issue by xosnrdev** [EOEboh/react-one-time-password#2]
## What's the idea?
Making an example interactive demo page for react-one-time-password. Creating a playground where devs can try out the package without installing it.

## Why is it needed?
1. Some devs aren't sure how the package works just by reading about it
2. Devs like to test things before they use them in their projects
3. It's hard to show all the cool features of the package in static README
4. A lot of questions can be answered by playing with the package

## How can we fix it?
Adding an interactive demo example that lets visitors:

1. Type in a custom one-time password
2. Change settings like timer duration or input style
3. See the component update in real-time
4. Copy the code for their custom setup

## Why is this good?
- Devs can understand the package better
- Devs can test if it fits their needs
- Fewer basic questions to answer
- It shows off all the cool things the package can do
- It might convince more people to use the package

**Comment by EOEboh** [comment]
Thank you for raising this issue @xosnrdev 
Can you work on it and raise a PR, so I can go through it myself.

**Comment by xosnrdev** [comment]
> Thank you for raising this issue @xosnrdev Can you work on it and raise a PR, so I can go through it myself.

Aight. I'll update this issue if I have any questions during implementation. Thank you
